### PR TITLE
Added basic directory listing fixing #32. Added 301 responses.

### PR DESCRIPTION
**Pull request by triforce**
* Extended thread buffer by 2048
* Added a very basic HTML formatted response with a list of the directory contents
* When request for a directory is a non forward slash terminated request a 301 is sent to the client, triggering their browser to request a forward slash terminated request.

### CODE REVIEW

**Comment by triforce** [comment]
@nemasu please test this thoroughly if you have a chance.

**Comment by nemasu** [comment]
This looks great! I will start testing it shortly.

**Comment by nemasu** [comment]
Sorry for the delay, I got around to testing it a bit.

I ran into a problem when I did something like this:
`cd web_root; mkdir dir1; touch dir1/{a,b,c}`

If I go to `localhost/dir1` the listing works, but when I click on one of them,
it tries to go to `localhost/dir1/a/` and then 404s instead of downloading a.

**Comment by triforce** [comment]
It think's 'a' is a directory for some reason. I will look into it.

**Comment by triforce** [comment]
Could you retest please @nemasu? It turned out to be quite a simple fix in the end!

**Comment by nemasu** [comment]
Hello, sorry for the *super* late reply.
I did some retesting, seems to be working so far!

There's 2 potential things though:
-Putting the previous directory ("...") at the top of the list.
-If 'index.html' exists in a directory, display that as default.

What do you think?

**Comment by nemasu** [comment]
Yeah that makes sense.
Funny you should mention config options, I was just thinking about how to go about disabling features to reduce binary size.

**Comment by nemasu** [comment]
To make thing easier though, I think we should do optional features as a separate issue after merging the directory code.

**Comment by triforce** [comment]
Yep makes sense.

**Comment by triforce** [comment]
@nemasu feel free to make those changes, I haven't had time recently unfortunately.

**Comment by nemasu** [comment]
Okay, I'll see if I can.

**Comment by triforce** [comment]
This is teetering on the edge of being finished @nemasu. There is just these two issues which you raised outstanding:

-Putting the previous directory ("...") at the top of the list.
-If 'index.html' exists in a directory, display that as default.

If anyone has some time then feel free to jump in and implement those two issues.

**Comment by triforce** [comment]
@nemasu after studying the code more closely it looks like requests to the root directory (and nothing else) adds the default document (index.html), so as part of the outstanding changes still required here we should remove that logic and create a more generic solution with directory listing functionality.

**Comment by nemasu** [comment]
Hello @triforce,
I'm finally looking at getting this committed, there are merge conflicts however since it's been ... a while, to say the least (sorry about that).

I've made your changes into a patch file relative to the current HEAD, if you like, you can close this PR and make a new one with the updated patch, and I'll accept it and work on the additions after. 

[directory_support.patch](https://github.com/nemasu/asmttpd/files/11184825/directory_support.patch)

**Comment by nemasu** [comment]
Merged in PR #58 .

**Pull request closed without merging**
